---
- name: install php packets
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_version_1 }}"
    - "{{ php_version_1 }}-mysql"
    - "{{ php_version_1 }}-fpm"

- name: copy configurate file to php
  template:
    src:  www.conf.j2
    dest: "/etc/{{ php_version_1 }}/fpm/pool.d/www.conf"
    backup: yes
  notify: reload php-fpm


