---
# install nginx
- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy nginx and jenkins config to /etc/nginx/ or /etc/nginx/conf.d
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf'}
    - { src: 'jenkins.conf.j2', dest: '/etc/nginx/conf.d/jenkins.conf'}
  notify: restart nginx