---
# install zeromq
- name: install zeromq packets
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libtool
    - autoconf
    - automake
    - uuid-dev
    - g++
    - python-dev

- name: unarchive zeromq
  unarchive:
    src: zeromq-4.2.0.tar.gz
    dest: /var/local

- name: make && make install zmq && ldconfig
  vars:
    ch:
  shell: "{{ item }}"
  with_items:
    - cd /var/local/zeromq-4.2.0/ && ./configure && make && make install
    - ldconfig

