---
# install mysql and create database
- name: install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python-dev
    - python-mysqldb

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify:
    - restart mysql

- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present
    config_file: /etc/mysql/my.cnf

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpasswd }}"
    priv: "*.*:ALL"
    host: "%"
    state: present